name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Backend Build and Test
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Backend Dependencies
        working-directory: .
        run: npm ci

      - name: Run Backend Tests
        working-directory: .
        run: npm test

      # Docker Build and Push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: omerbenda98/server-heroku:${{ github.sha }}

      # Checkout and update K8s repo
      - name: Checkout K8s repository
        uses: actions/checkout@v4
        with:
          repository: omerbenda98/puppy-adoption-k8s
          token: ${{ secrets.K8S_REPO_TOKEN }}
          path: k8s-repo

      - name: Update Kubernetes deployment
        run: |
          cd k8s-repo
          sed -i 's|image: omerbenda98/server-heroku:.*|image: omerbenda98/server-heroku:${{ github.sha }}|' development/backend/deployment.yaml
          sed -i 's|image: omerbenda98/server-heroku:.*|image: omerbenda98/server-heroku:${{ github.sha }}|' production/backend/deployment.yaml

      - name: Commit updated manifests
        run: |
          cd k8s-repo
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git

# name: Deploy to Heroku

# on:
#   push:
#     branches:
#       - main  # or your default branch

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: '20'  # or your preferred version
#       - run: npm ci
#       - run: npm test

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: akhileshns/heroku-deploy@v3.12.14
#         with:
#           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#           heroku_app_name: "dog-adopt-app"
#           heroku_email: "omerbenda98@gmail.com"
